# anonymize.awk - Generate PII anonymization SQL from schema dump + YAML config
# BSD awk compatible (macOS). Receives variables via -v:
#   prefix       - REMOTE_DB_PREFIX
#   config_file  - path to pipe-delimited config: table|column|converter|param_value|param_formatter
#   eav_file     - path to pipe-delimited EAV config: eav_table|entity_type|attribute_code|converter

BEGIN {
    pw_hash = "7fba49a86bb6de7e79f92d64fe8aa6b8d16fd0b98063913327c1ca04c833dc39:warden:1"

    # Read config file into arrays
    cfg_count = 0
    while ((getline line < config_file) > 0) {
        n = split(line, parts, "|")
        if (n >= 3) {
            cfg_count++
            cfg_table[cfg_count] = parts[1]
            cfg_column[cfg_count] = parts[2]
            cfg_converter[cfg_count] = parts[3]
            cfg_param_value[cfg_count] = (n >= 4) ? parts[4] : ""
            cfg_param_fmt[cfg_count] = (n >= 5) ? parts[5] : ""

            # Index by table for fast lookup
            if (!(parts[1] in table_has_config)) {
                table_has_config[parts[1]] = 1
            }
        }
    }
    close(config_file)

    # Read EAV config file: eav_table|entity_type|attribute_code|converter
    eav_count = 0
    if (eav_file != "") {
        while ((getline line < eav_file) > 0) {
            n = split(line, parts, "|")
            if (n >= 4) {
                eav_count++
                eav_table[eav_count] = parts[1]
                eav_entity_type[eav_count] = parts[2]
                eav_attr_code[eav_count] = parts[3]
                eav_converter[eav_count] = parts[4]

                # Track which EAV tables we need to look for in schema
                eav_tables_needed[parts[1]] = 1
            }
        }
        close(eav_file)
    }

    in_table = 0
    col_count = 0
    printed_header = 0
}

# Stop processing at data section
/^INSERT INTO/ { exit 0 }

# Detect CREATE TABLE
/^CREATE TABLE/ {
    line = $0
    sub(/^CREATE TABLE `/, "", line)
    sub(/` \(.*/, "", line)
    current_table = line

    # Strip prefix to get bare name
    if (prefix != "" && index(current_table, prefix) == 1) {
        bare_table = substr(current_table, length(prefix) + 1)
    } else {
        bare_table = current_table
    }

    in_table = 1
    col_count = 0
    pk_col = ""
    delete col_names

    # Track EAV tables found in schema (bare_table → prefixed_table)
    if (bare_table in eav_tables_needed) {
        eav_tables_found[bare_table] = current_table
    }
    delete col_exists
    delete uniq_cols

    next
}

# End of CREATE TABLE
in_table && /^\) ENGINE/ {
    in_table = 0

    # Skip view stubs (ENGINE=MyISAM with only 1 column)
    if ($0 ~ /ENGINE=MyISAM/ && col_count == 1) next

    # Skip tables with no config
    if (!(bare_table in table_has_config)) next

    # Collect matching converters for this table
    update_count = 0
    delete update_cols
    delete update_convs
    delete update_params
    delete update_fmts

    for (i = 1; i <= cfg_count; i++) {
        if (cfg_table[i] == bare_table && (cfg_column[i] in col_exists)) {
            update_count++
            update_cols[update_count] = cfg_column[i]
            update_convs[update_count] = cfg_converter[i]
            update_params[update_count] = cfg_param_value[i]
            update_fmts[update_count] = cfg_param_fmt[i]
        }
    }

    if (update_count > 0) {
        if (!printed_header) {
            print "-- Anonymization generated by warden db-dump"
            print "SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;"
            print ""
            printed_header = 1
        }
        print "-- " current_table
        for (i = 1; i <= update_count; i++) {
            emit_update(current_table, update_cols[i], update_convs[i], update_params[i], update_fmts[i], pk_col)
        }
        print ""
    }

    next
}

# Inside CREATE TABLE - collect columns, PK, UNIQUE keys
in_table {
    line = $0
    sub(/^[ \t]+/, "", line)

    # Parse PRIMARY KEY
    if (line ~ /^PRIMARY KEY/) {
        pk = line
        sub(/^PRIMARY KEY \(`/, "", pk)
        sub(/`\).*/, "", pk)
        if (pk !~ /`,`/) pk_col = pk
        next
    }

    # Parse UNIQUE KEY (single-column only)
    if (line ~ /^UNIQUE KEY/) {
        uk = line
        sub(/^UNIQUE KEY [^(]+\(`/, "", uk)
        sub(/`\).*/, "", uk)
        if (uk !~ /`,`/) uniq_cols[uk] = 1
        next
    }

    # Skip other index/constraint lines
    if (line ~ /^(KEY|FULLTEXT|SPATIAL|CONSTRAINT|INDEX|CHECK)/) next

    # Must start with backtick (column definition)
    if (line !~ /^`/) next

    # Extract column name
    cn = line
    sub(/^`/, "", cn)
    sub(/`.*/, "", cn)

    col_count++
    col_names[col_count] = cn
    col_exists[cn] = 1
}

END {
    # Emit EAV anonymization UPDATEs
    if (eav_count > 0) {
        first_eav = 1
        for (i = 1; i <= eav_count; i++) {
            bt = eav_table[i]
            if (!(bt in eav_tables_found)) continue

            prefixed_table = eav_tables_found[bt]
            ea_tbl = prefix "eav_attribute"
            eet_tbl = prefix "eav_entity_type"

            if (first_eav) {
                if (!printed_header) {
                    print "-- Anonymization generated by warden db-dump"
                    print "SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;"
                    print ""
                    printed_header = 1
                }
                print "-- EAV attribute anonymization"
                first_eav = 0
            }

            # Determine SET clause based on converter and value table type
            conv = eav_converter[i]
            # Infer value table type from table name suffix
            vtype = bt
            sub(/^.*_entity_/, "", vtype)
            sub(/^.*_/, "", vtype)

            if (conv == "hashValue") {
                set_clause = "cev.`value` = LEFT(SHA2(cev.`value`, 256), 12)"
                where_extra = ""
            } else if (conv == "randomizeEmail") {
                set_clause = "cev.`value` = CONCAT(LEFT(SHA2(cev.`value`, 256), 12), '@warden.test')"
                where_extra = " AND cev.`value` NOT LIKE '%@warden.test'"
            } else if (conv == "randomizeText") {
                set_clause = "cev.`value` = 'REDACTED'"
                where_extra = ""
            } else if (conv == "randomizeNumber") {
                set_clause = "cev.`value` = '0000000000'"
                where_extra = ""
            } else if (conv == "setNull") {
                set_clause = "cev.`value` = NULL"
                where_extra = " AND cev.`value` IS NOT NULL"
            } else {
                set_clause = "cev.`value` = 'REDACTED'"
                where_extra = ""
            }

            printf "UPDATE IGNORE `%s` AS cev ", prefixed_table
            printf "INNER JOIN `%s` AS ea ON cev.attribute_id = ea.attribute_id ", ea_tbl
            printf "INNER JOIN `%s` AS eet ON ea.entity_type_id = eet.entity_type_id ", eet_tbl
            printf "SET %s ", set_clause
            printf "WHERE ea.attribute_code = '%s' ", eav_attr_code[i]
            printf "AND eet.entity_type_code = '%s' ", eav_entity_type[i]
            printf "AND ea.backend_type != 'static'%s;\n", where_extra
        }
        if (!first_eav) print ""
    }

    if (printed_header) {
        print "SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;"
    }
}

function emit_update(tbl, col, converter, param_val, param_fmt, pk) {
    if (converter == "randomizeEmail") {
        printf "UPDATE IGNORE `%s` SET `%s` = CONCAT(LEFT(SHA2(`%s`, 256), 12), '@warden.test') WHERE `%s` IS NOT NULL AND `%s` NOT LIKE '%%@warden.test';\n", tbl, col, col, col, col

    } else if (converter == "randomizeText") {
        emit_randomize_text(tbl, col, pk)

    } else if (converter == "randomizeNumber") {
        printf "UPDATE IGNORE `%s` SET `%s` = '0000000000' WHERE `%s` IS NOT NULL AND `%s` != '0000000000';\n", tbl, col, col, col

    } else if (converter == "setNull") {
        printf "UPDATE IGNORE `%s` SET `%s` = NULL WHERE `%s` IS NOT NULL;\n", tbl, col, col

    } else if (converter == "setValue") {
        if (param_val ~ /^[0-9]+$/) {
            printf "UPDATE IGNORE `%s` SET `%s` = %s;\n", tbl, col, param_val
        } else {
            printf "UPDATE IGNORE `%s` SET `%s` = '%s' WHERE `%s` IS NOT NULL;\n", tbl, col, param_val, col
        }

    } else if (converter == "setPassword") {
        printf "UPDATE IGNORE `%s` SET `%s` = '%s' WHERE `%s` IS NOT NULL;\n", tbl, col, pw_hash, col

    } else if (converter == "anonymizeDate" || converter == "anonymizeDateTime") {
        printf "UPDATE IGNORE `%s` SET `%s` = NULL WHERE `%s` IS NOT NULL;\n", tbl, col, col

    } else if (converter == "faker") {
        if (param_fmt == "ipv4") {
            printf "UPDATE IGNORE `%s` SET `%s` = '127.0.0.1' WHERE `%s` IS NOT NULL;\n", tbl, col, col
        }

    } else if (converter == "hashValue") {
        printf "UPDATE IGNORE `%s` SET `%s` = LEFT(SHA2(`%s`, 256), 12) WHERE `%s` IS NOT NULL;\n", tbl, col, col, col

    } else if (converter == "jsonMethodTitle") {
        printf "UPDATE IGNORE `%s` SET `%s` = IF(JSON_VALID(`%s`) AND JSON_EXTRACT(`%s`, '$.method_title') IS NOT NULL, JSON_OBJECT('method_title', JSON_UNQUOTE(JSON_EXTRACT(`%s`, '$.method_title'))), '{}') WHERE `%s` IS NOT NULL;\n", tbl, col, col, col, col, col
    }
}

# Infer replacement value from column name for randomizeText
function emit_randomize_text(tbl, col, pk) {
    if (col ~ /firstname/) {
        emit_const_or_pk(tbl, col, "'Anon'", pk)
    } else if (col ~ /lastname/) {
        emit_const_or_pk(tbl, col, "'Customer'", pk)
    } else if (col ~ /middlename/) {
        printf "UPDATE IGNORE `%s` SET `%s` = NULL WHERE `%s` IS NOT NULL;\n", tbl, col, col
    } else if (col ~ /username/) {
        if (pk != "") {
            printf "UPDATE IGNORE `%s` SET `%s` = CONCAT('admin', `%s`) WHERE `%s` IS NOT NULL;\n", tbl, col, pk, col
        } else {
            printf "UPDATE IGNORE `%s` SET `%s` = 'admin_anon' WHERE `%s` IS NOT NULL;\n", tbl, col, col
        }
    } else if (col ~ /nickname/) {
        emit_const_or_pk(tbl, col, "'Anonymous'", pk)
    } else if (col ~ /track/) {
        printf "UPDATE IGNORE `%s` SET `%s` = 'ANON000000' WHERE `%s` IS NOT NULL;\n", tbl, col, col
    } else if (col ~ /company/) {
        printf "UPDATE IGNORE `%s` SET `%s` = 'Anonymous Co' WHERE `%s` IS NOT NULL;\n", tbl, col, col
    } else if (col ~ /street/) {
        printf "UPDATE IGNORE `%s` SET `%s` = '123 Anonymous St' WHERE `%s` IS NOT NULL;\n", tbl, col, col
    } else if (col ~ /city/) {
        printf "UPDATE IGNORE `%s` SET `%s` = 'Anytown' WHERE `%s` IS NOT NULL;\n", tbl, col, col
    } else if (col ~ /(address|full|shipping_information)/) {
        printf "UPDATE IGNORE `%s` SET `%s` = 'Anon Customer, 123 Anonymous St' WHERE `%s` IS NOT NULL;\n", tbl, col, col
    } else if (col ~ /name/) {
        emit_const_or_pk(tbl, col, "'Anon Customer'", pk)
    } else {
        printf "UPDATE IGNORE `%s` SET `%s` = 'REDACTED' WHERE `%s` IS NOT NULL;\n", tbl, col, col
    }
}

# Use PK-based value if column has UNIQUE constraint, otherwise constant
function emit_const_or_pk(tbl, col, const_val, pk) {
    if ((col in uniq_cols) && pk != "") {
        printf "UPDATE IGNORE `%s` SET `%s` = CONCAT(%s, ' ', `%s`) WHERE `%s` IS NOT NULL;\n", tbl, col, const_val, pk, col
    } else {
        printf "UPDATE IGNORE `%s` SET `%s` = %s WHERE `%s` IS NOT NULL AND `%s` != %s;\n", tbl, col, const_val, col, col, const_val
    }
}
