#!/usr/bin/env bash
[[ ! ${WARDEN_DIR} ]] && >&2 echo -e "\033[31mThis script is not intended to be run directly!\033[0m" && exit 1

set -euo pipefail

function :: {
  echo
  echo -e "\033[33m$@\033[0m"
}

WARDEN_ENV_PATH="$(locateEnvPath)" || exit $?

loadEnvConfig "${WARDEN_ENV_PATH}" || exit $?
eval "$(cat "${WARDEN_ENV_PATH}/.env" | sed 's/\r$//g' | grep "^CLOUD_")"

## verify Den version constraint
DEN_VERSION=$(den version 2>/dev/null) || true
DEN_REQUIRE=1.0.0
if ! test $(version ${DEN_VERSION}) -ge $(version ${DEN_REQUIRE}); then
  error "Den ${DEN_REQUIRE} or greater is required (version ${DEN_VERSION} is installed)"
  exit 3
fi

assertDockerRunning

cd "${WARDEN_ENV_PATH}"
